security.protocol=SSL
ssl.truststore.location=ssl/clients/consumer/consumer.truststore.p12
ssl.truststore.password=mypass123
ssl.truststore.type=PKCS12
ssl.keystore.location=ssl/clients/consumer/consumer.keystore.p12
ssl.keystore.password=mypass123
ssl.keystore.type=PKCS12
ssl.key.password=mypass123
ssl.endpoint.identification.algorithm=
