# Kafka broker 2 - SSL + ACL
broker.id=2
zookeeper.connect=zookeeper:2181

listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL
listeners=PLAINTEXT://0.0.0.0:29092,SSL://0.0.0.0:9092
advertised.listeners=PLAINTEXT://kafka2:29092,SSL://localhost:9093
inter.broker.listener.name=PLAINTEXT

ssl.keystore.location=/etc/kafka/secrets/kafka2.keystore.p12
ssl.keystore.password=mypass123
ssl.keystore.type=PKCS12
ssl.key.password=mypass123
ssl.truststore.location=/etc/kafka/secrets/kafka2.truststore.p12
ssl.truststore.password=mypass123
ssl.truststore.type=PKCS12
ssl.client.auth=requested
ssl.endpoint.identification.algorithm=

authorizer.class.name=kafka.security.authorizer.AclAuthorizer
allow.everyone.if.no.acl.found=false
super.users=User:admin;User:ANONYMOUS
ssl.principal.mapping.rules=RULE:^.*CN=([^,]*).*$/$1/L,DEFAULT

offsets.topic.replication.factor=2
transaction.state.log.replication.factor=2
transaction.state.log.min.isr=2
default.replication.factor=2
min.insync.replicas=2

auto.create.topics.enable=false
delete.topic.enable=true

log.dirs=/var/lib/kafka/data
